// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo_zz-sHdQQGl-WcMYbZjGZkoVR4FVqSE',
    appId: '1:971581267438:web:525bd2170b4ed1111d42ff',
    messagingSenderId: '971581267438',
    projectId: 'todo-e38b0',
    authDomain: 'todo-e38b0.firebaseapp.com',
    storageBucket: 'todo-e38b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB93VkZXzTSqD9ZwVXlvHRPCRbAUZx8oK8',
    appId: '1:971581267438:android:cd0de7659083ef841d42ff',
    messagingSenderId: '971581267438',
    projectId: 'todo-e38b0',
    storageBucket: 'todo-e38b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKCMhjeU15P_PFlkselHnq3HqkF-BUTM',
    appId: '1:971581267438:ios:ba54db65033b71ae1d42ff',
    messagingSenderId: '971581267438',
    projectId: 'todo-e38b0',
    storageBucket: 'todo-e38b0.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
